/**
 * Rotary positional embeddings, ported from `src/llmfs/model/rope.py`.
 *
 * This is a second implementation of something the repository already implements in
 * PyTorch, which is normally a smell. It exists because the visualization would
 * otherwise be an *illustration* of RoPE rather than a picture of the code that
 * actually trains the models here — and those drift apart silently. `rope.test.ts`
 * pins this port against a fixture generated by the Python implementation, so a
 * change to one that is not mirrored in the other fails CI.
 *
 * Convention, identical to the Python: the "split-half" pairing from GPT-NeoX and
 * HF Llama, where dimension `i` is paired with `i + headDim/2` — *not* the adjacent
 * `(2i, 2i+1)` pairing of the original paper.
 */

/** Angular velocity of each dimension pair: `invFreq[i] = theta^(-2i/headDim)`. */
export function invFreqs(headDim: number, theta = 10_000): Float64Array {
  if (headDim % 2 !== 0) throw new Error(`RoPE requires an even headDim, got ${headDim}`);
  const half = headDim / 2;
  const out = new Float64Array(half);
  for (let i = 0; i < half; i++) out[i] = 1 / theta ** ((2 * i) / headDim);
  return out;
}

/**
 * The rotation angle applied to each dimension pair for a token at `pos`.
 *
 * Pair 0 turns a full revolution every ~6.3 positions; the last pair barely moves
 * across the whole context. That spread is the mechanism — fast pairs resolve
 * neighbouring tokens, slow pairs carry long-range order.
 */
export function pairAngles(pos: number, headDim: number, theta = 10_000): Float64Array {
  const inv = invFreqs(headDim, theta);
  const out = new Float64Array(inv.length);
  for (let i = 0; i < inv.length; i++) out[i] = pos * inv[i]!;
  return out;
}

/**
 * Rotate one vector as if it sat at position `pos`.
 *
 * Mirrors `apply_rotary_emb`: `x * cos + rotate_half(x) * sin`, where `rotate_half`
 * maps `[x1, x2] -> [-x2, x1]` across the half-way split.
 */
export function rotate(x: ArrayLike<number>, pos: number, theta = 10_000): Float64Array {
  const headDim = x.length;
  const half = headDim / 2;
  const inv = invFreqs(headDim, theta);
  const out = new Float64Array(headDim);
  for (let i = 0; i < half; i++) {
    const angle = pos * inv[i]!;
    const c = Math.cos(angle);
    const s = Math.sin(angle);
    const a = x[i]!;
    const b = x[i + half]!;
    out[i] = a * c - b * s;
    out[i + half] = b * c + a * s;
  }
  return out;
}

export function dot(a: ArrayLike<number>, b: ArrayLike<number>): number {
  let total = 0;
  for (let i = 0; i < a.length; i++) total += a[i]! * b[i]!;
  return total;
}

/** The attention logit (pre-scaling) for a query at `m` against a key at `n`. */
export function dotRotated(
  q: ArrayLike<number>,
  k: ArrayLike<number>,
  m: number,
  n: number,
  theta = 10_000,
): number {
  return dot(rotate(q, m, theta), rotate(k, n, theta));
}

/**
 * The same logit computed from the relative offset alone, never forming either
 * absolute position.
 *
 * Composing a rotation by `mθ` with the inverse of a rotation by `nθ` leaves
 * `(m-n)θ`, so per pair the whole dependence on position collapses to:
 *
 *     (qᵢkᵢ + qᵢ₊ₕkᵢ₊ₕ)·cos(dθᵢ) + (qᵢkᵢ₊ₕ − qᵢ₊ₕkᵢ)·sin(dθᵢ)
 *
 * That this agrees with {@link dotRotated} to floating-point noise *is* the
 * property `tests/test_rope.py` asserts, and it is what the explorer draws.
 */
export function dotRelative(
  q: ArrayLike<number>,
  k: ArrayLike<number>,
  d: number,
  theta = 10_000,
): number {
  const half = q.length / 2;
  const inv = invFreqs(q.length, theta);
  let total = 0;
  for (let i = 0; i < half; i++) {
    const angle = d * inv[i]!;
    total +=
      (q[i]! * k[i]! + q[i + half]! * k[i + half]!) * Math.cos(angle) +
      (q[i]! * k[i + half]! - q[i + half]! * k[i]!) * Math.sin(angle);
  }
  return total;
}

/** Per-pair contribution to the logit, for the dials in the explorer. */
export function pairContributions(
  q: ArrayLike<number>,
  k: ArrayLike<number>,
  d: number,
  theta = 10_000,
): Float64Array {
  const half = q.length / 2;
  const inv = invFreqs(q.length, theta);
  const out = new Float64Array(half);
  for (let i = 0; i < half; i++) {
    const angle = d * inv[i]!;
    out[i] =
      (q[i]! * k[i]! + q[i + half]! * k[i + half]!) * Math.cos(angle) +
      (q[i]! * k[i + half]! - q[i + half]! * k[i]!) * Math.sin(angle);
  }
  return out;
}

/**
 * A deterministic stand-in for a learned q/k vector.
 *
 * mulberry32 — small, seeded, and identical across browsers, so a link to this page
 * shows the reader the same picture the author was looking at.
 */
export function seededVector(headDim: number, seed: number): Float64Array {
  let s = seed >>> 0;
  const rand = () => {
    s = (s + 0x6d2b79f5) >>> 0;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  const out = new Float64Array(headDim);
  // Box-Muller, then unit-normalised: real q/k vectors are not unit vectors, but a
  // fixed norm keeps the dot product readable as "alignment" while a slider moves.
  for (let i = 0; i < headDim; i++) {
    const u = Math.max(rand(), 1e-12);
    const v = rand();
    out[i] = Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
  }
  let norm = 0;
  for (let i = 0; i < headDim; i++) norm += out[i]! * out[i]!;
  norm = Math.sqrt(norm) || 1;
  for (let i = 0; i < headDim; i++) out[i] = out[i]! / norm;
  return out;
}
