import { ARCHITECTURES } from "./architecture";
import { GPT2_124M, LLAMA_124M, type SizeConfig, headDim, mlpHidden, parameters } from "../lib/modelsize";

/**
 * The stack, block by block — one class, two architectures, decided by config.
 *
 * Every parameter count here comes from `modelsize.ts`, which is fixture-pinned to the
 * real `Transformer` across twelve configurations, and every config value from
 * `architecture.ts`, generated by resolving the shipped YAML through the repository's
 * own loader. Nothing on this page is arithmetic anybody did by hand.
 *
 * The `pins` sentence on each block names a test. Each one was written by reading that
 * test, not by reading its name: a page whose entire argument is *this is pinned* is the
 * worst possible place to be wrong about what is pinned. Where a block has no test that
 * asserts a property — only shape checks — it says so instead of borrowing one.
 */

export type Variant = "gpt2" | "llama";

export const SIZES: Record<Variant, SizeConfig> = { gpt2: GPT2_124M, llama: LLAMA_124M };

export type Block = {
  id: string;
  title: string;
  /** What it does, in one line, for a reader scanning the column. */
  summary: string;
  /** How many of these the stack holds — `n_layer` for the repeated ones. */
  repeat?: (v: Variant) => number;
  /** The detail panel's body. */
  what: string;
  /** Which of the two architectures differ here, and how. */
  differs?: (v: Variant) => string | null;
  /** Parameters attributable to this block, or null when it holds none. */
  params: (v: Variant) => number | null;
  /** Shape, as the reader would write it. */
  shape: (v: Variant) => string;
  /** The test that pins it, and what that test actually asserts. */
  pins: { test: string; claim: string } | null;
};

const cfg = (v: Variant) => SIZES[v];
const resolved = (v: Variant) => ARCHITECTURES[v].config;
const p = (v: Variant) => parameters(cfg(v));

export const BLOCKS: Block[] = [
  {
    id: "token-embedding",
    title: "Token embedding",
    summary: "One row per vocabulary entry — a lookup, before any computation happens",
    what:
      "The only thing the model ever sees is a list of integers, and this table is what turns each of them into a vector. It is a lookup, not a matrix multiply: no arithmetic happens here at all. It is also, at this scale, a third of the entire parameter budget — which is why 4-bit quantization of the weights caps out at 2.42× compression rather than the 8× the bit width suggests.",
    params: (v) => p(v).tokenEmbedding,
    shape: (v) => `${resolved(v).vocabSize.toLocaleString()} × ${resolved(v).nEmbd}`,
    pins: {
      test: "web/src/lib/modelsize.test.ts",
      claim:
        "that this page's arithmetic reproduces the real Transformer's parameter count exactly — not approximately — across twelve configurations, against a fixture generated by instantiating the model and summing p.numel().",
    },
  },
  {
    id: "position",
    title: "Position",
    summary: "Where each token sits — a learned table, or a rotation applied inside attention",
    what:
      "Attention is a weighted average, and an average has no notion of order: shuffle the tokens and the output is the same. Something has to reintroduce position. GPT-2 learns a vector per absolute slot and adds it; RoPE instead rotates the query and key vectors by an angle proportional to position, so the attention logit between two tokens depends only on the distance between them.",
    differs: (v) =>
      v === "gpt2"
        ? "A learned table of block_size vectors, added to the embedding. It holds parameters and cannot extrapolate past its last row."
        : "No parameters at all — a rotation applied to q and k inside every attention layer, so the same table serves any length.",
    params: (v) => p(v).positionEmbedding || null,
    shape: (v) =>
      resolved(v).posEmb === "learned"
        ? `${resolved(v).blockSize} × ${resolved(v).nEmbd} table`
        : `θ = ${resolved(v).ropeTheta.toLocaleString()}, applied to ${headDim(cfg(v))} dims per head`,
    pins: {
      test: "test_rope.py::test_relative_position_property",
      claim:
        "that ⟨R(q, m), R(k, n)⟩ depends only on m − n, to 1e-6 — the defining property, which no shape check implies.",
    },
  },
  {
    id: "norm",
    title: "Normalisation",
    summary: "Applied before each sub-layer, not after — the pre-norm arrangement",
    what:
      "Two per block: one before attention, one before the feed-forward, plus a final one before the output head. Pre-norm rather than post-norm, which is what lets the residual stream run from input to output without a normalisation in the way — the reason deep stacks train at all without warmup tricks. RMSNorm drops the mean-centring and the bias, so it is cheaper and carries half the parameters, while measurably doing nothing to loss.",
    repeat: (v) => 2 * resolved(v).nLayer + 1,
    differs: (v) =>
      v === "gpt2"
        ? "LayerNorm: centres and scales, with a learned gain and bias."
        : "RMSNorm: scales only, with a learned gain and no bias. The reduction is taken in fp32 regardless of the activation dtype.",
    params: (v) => p(v).norms,
    shape: (v) => `${2 * resolved(v).nLayer + 1} × ${resolved(v).nEmbd}${resolved(v).norm === "layernorm" ? " (gain + bias)" : " (gain)"}`,
    pins: null,
  },
  {
    id: "attention",
    title: "Attention",
    summary: "Every token looks back at the ones before it — the only place they interact",
    what:
      "One fused projection produces queries, keys and values; the causal mask is what stops a token attending to its own future. This is the only sub-layer in the whole stack where positions communicate — the feed-forward, the norms and the head all act on each position independently — so every claim about context is a claim about this block.",
    repeat: (v) => resolved(v).nLayer,
    differs: (v) =>
      v === "gpt2"
        ? `${resolved(v).nHead} query heads and ${resolved(v).nKvHead} key/value heads — one KV head per query head.`
        : `${resolved(v).nHead} query heads sharing ${resolved(v).nKvHead} key/value heads, so the cache is ${resolved(v).nHead / resolved(v).nKvHead}× smaller for the same query capacity.`,
    params: (v) => p(v).attention,
    shape: (v) =>
      `${resolved(v).nLayer} × [qkv ${resolved(v).nEmbd}→${(resolved(v).nHead + 2 * resolved(v).nKvHead) * headDim(cfg(v))}, out ${resolved(v).nEmbd}→${resolved(v).nEmbd}]`,
    pins: {
      test: "test_attention.py::test_causality",
      claim:
        "that perturbing token t leaves every position before t bitwise unchanged, across all ten architecture variants. An off-by-one mask makes the loss look better, so no curve would catch it.",
    },
  },
  {
    id: "feed-forward",
    title: "Feed-forward",
    summary: "Widen, apply a non-linearity, project back — per position, independently",
    what:
      "Two thirds of the compute in a transformer block and roughly two thirds of its parameters. It sees one position at a time, which is what makes it cheap to parallelise and what makes attention the only interesting part of the architecture for context length.",
    repeat: (v) => resolved(v).nLayer,
    differs: (v) =>
      v === "gpt2"
        ? `GELU at ${resolved(v).mlpRatio}× width — two matrices, up and down.`
        : `SwiGLU at ${resolved(v).mlpRatio}× width scaled by 2/3 and rounded to a multiple of ${resolved(v).mlpHiddenMultipleOf}. Three matrices rather than two, so the 2/3 keeps the parameter count comparable with GELU's.`,
    params: (v) => p(v).feedForward,
    shape: (v) =>
      `${resolved(v).nLayer} × [${resolved(v).nEmbd} → ${mlpHidden(cfg(v)).toLocaleString()} → ${resolved(v).nEmbd}]`,
    pins: null,
  },
  {
    id: "blocks",
    title: `The block, repeated`,
    summary: "Norm → attention → residual, norm → feed-forward → residual",
    what:
      "Everything above, stacked. The residual connections are the reason depth is survivable: each block adds to a running stream rather than replacing it, so the gradient has a path to the input that does not pass through any transformation. The output projections of both sub-layers are initialised at 1/√(2·n_layer) so that the stream's variance does not grow with depth.",
    repeat: (v) => resolved(v).nLayer,
    params: (v) => p(v).attention + p(v).feedForward + p(v).norms,
    shape: (v) => `${resolved(v).nLayer} blocks, ${resolved(v).nEmbd} wide`,
    pins: {
      test: "test_model.py::test_residual_init_is_downscaled",
      claim:
        "that residual output projections are initialised with the 1/√(2·n_layer) scaling rather than the default.",
    },
  },
  {
    id: "final-norm",
    title: "Final norm",
    summary: "One last normalisation before the output head",
    what:
      "Pre-norm leaves the residual stream un-normalised at the top of the stack, so one more is needed before the head reads it. Easy to omit and hard to notice: the model still trains, slightly worse, for no visible reason.",
    params: () => null,
    shape: (v) => `${resolved(v).nEmbd}${resolved(v).norm === "layernorm" ? " (gain + bias)" : " (gain)"}`,
    pins: null,
  },
  {
    id: "output-head",
    title: "Output head",
    summary: "Back to one score per vocabulary entry — the same matrix as the embedding",
    what:
      "The head projects the final hidden state to a logit per token. Both configs tie it to the token embedding, so it adds no parameters at all: the same matrix maps ids to vectors on the way in and vectors to scores on the way out. Untying would add 38.6M parameters — about five and a half more blocks' worth — and it is also why the quantizer refuses to quantize the head while the weights are tied, since that would store a compressed copy beside the original and make the model larger.",
    differs: (v) =>
      resolved(v).tieEmbeddings
        ? "Tied to the token embedding — zero additional parameters."
        : "Untied — a full second vocabulary-sized matrix.",
    params: (v) => p(v).lmHead || null,
    shape: (v) => `${resolved(v).nEmbd} → ${resolved(v).vocabSize.toLocaleString()}`,
    pins: {
      test: "test_model.py::test_tying_couples_gradients",
      claim:
        "that both roles of the shared matrix contribute to its one gradient — tying implemented as a copy would train and converge while quietly starving the input table of half its signal.",
    },
  },
  {
    id: "kv-cache",
    title: "KV cache",
    summary: "Not a layer — the state that makes generation cheaper than re-reading",
    what:
      "During generation every step would otherwise recompute keys and values for the entire prefix. The cache is preallocated at the maximum sequence length and written in place, so decoding one token costs one token of work. It holds no parameters; it holds memory, and the figure below is per sequence at full context.",
    differs: (v) =>
      `${resolved(v).nKvHead} KV heads × ${headDim(cfg(v))} dims × 2 (K and V) × ${resolved(v).nLayer} layers.`,
    params: () => null,
    shape: (v) => {
      const bytes = 2 * 2 * resolved(v).nLayer * resolved(v).nKvHead * headDim(cfg(v)) * resolved(v).blockSize;
      return `${(bytes / 1024 / 1024).toFixed(1)} MiB per sequence at ${resolved(v).blockSize} tokens, fp16`;
    },
    pins: {
      test: "test_kv_cache.py::test_incremental_decode_matches_full_forward",
      claim:
        "that token-at-a-time decoding reproduces a full forward pass at every position, across all ten variants. Training never exercises the cache, so nothing else would catch a stale offset or a double-rotated key.",
    },
  },
];
