#!/usr/bin/env bash
#
# Runs ON the GPU pod. Installs the package against a torch build that can actually
# drive the card, and verifies that before any paid work starts. Idempotent.
#
# The subtlety this exists to handle: newer GPUs need a torch built for their compute
# capability. An RTX 5090 is Blackwell (sm_120) and needs a cu128 build; a generic
# PyPI wheel may carry no sm_120 kernels and dies at the first matmul with "no kernel
# image is available for execution on the device" — after the install looked fine.
# RunPod's PyTorch templates already ship a build matched to the card, so the rule
# here is: if the image's torch works on this GPU, keep it and install around it.
# Only fall back to installing torch when there is nothing usable.
#
# Invoked by scripts/gpu.sh setup; not usually run by hand.

set -euo pipefail

WORKDIR="${GPU_WORKDIR:-/workspace}"
REPO="$WORKDIR/LLMfromScratch"
CUDA_INDEX="${CUDA_INDEX:-https://download.pytorch.org/whl/cu128}"

cd "$REPO"

echo "--- system packages ---"
if ! command -v tmux >/dev/null || ! command -v rsync >/dev/null; then
  apt-get update -qq >/dev/null 2>&1 || true
  apt-get install -y -qq tmux rsync git >/dev/null 2>&1 || true
fi
command -v tmux >/dev/null || { echo "FATAL: tmux missing and could not be installed" >&2; exit 1; }

# ---------------------------------------------------------------- torch strategy

# Does the image's torch exist, see the GPU, and successfully run a kernel on it?
# The matmul is the real test — torch.cuda.is_available() returns True even when the
# build has no kernels for this architecture.
probe_torch() {
  local py="$1"
  "$py" - <<'PY' >/dev/null 2>&1
import torch
assert torch.cuda.is_available()
a = torch.randn(256, 256, device="cuda", dtype=torch.bfloat16)
(a @ a).sum().item()
PY
}

SYS_PY="$(command -v python3)"
USE_SYSTEM_TORCH=0
# LLMFS_FORCE_TORCH_INSTALL=1 skips the image's torch even when it works, so a fresh
# build is installed from CUDA_INDEX instead. Keeping the image's torch is the right
# default — it is matched to the card — but it means two different pods get two different
# torch builds, and therefore two different NCCL versions. When the measurement *is* the
# collective (the multi-GPU scaling study compares one machine's all-reduce against
# another's), that difference is a confound rather than a detail, so both pods have to be
# pinned to the same build even if it is not each image's favourite.
if [[ "${LLMFS_FORCE_TORCH_INSTALL:-0}" == "1" ]]; then
  echo "--- torch ---"
  echo "LLMFS_FORCE_TORCH_INSTALL=1: ignoring the image's torch, installing from $CUDA_INDEX"
elif [[ -n "$SYS_PY" ]] && probe_torch "$SYS_PY"; then
  USE_SYSTEM_TORCH=1
  echo "--- torch ---"
  echo "image torch runs kernels on this GPU; keeping it"
  "$SYS_PY" -c "import torch;print(f'  torch {torch.__version__}  cuda {torch.version.cuda}')"
else
  echo "--- torch ---"
  echo "image torch is missing or cannot run kernels on this GPU; installing from $CUDA_INDEX"
fi

echo "--- installing llmfs ---"
if [[ "$USE_SYSTEM_TORCH" == "1" ]]; then
  # Install into the image's interpreter so the working torch is the one used.
  # torch>=2.4 is already satisfied, so pip leaves it alone.
  # Not --quiet. This install pulls a few hundred MB (datasets, wandb, tensorboard,
  # matplotlib, pandas) and takes minutes; with --quiet it emits nothing at all, which is
  # indistinguishable from a hang to whoever is watching a pod bill by the minute. The
  # progress bars are suppressed instead, so the log stays readable but keeps moving.
  PIP_ARGS=(--no-input --progress-bar off)
  if ! "$SYS_PY" -m pip install "${PIP_ARGS[@]}" -e ".[train,bench]" 2>/dev/null; then
    # Ubuntu 24.04 marks the system interpreter externally-managed (PEP 668).
    "$SYS_PY" -m pip install "${PIP_ARGS[@]}" --break-system-packages -e ".[train,bench]"
  fi
  LLMFS_PY="$SYS_PY"
else
  if ! command -v uv >/dev/null && [[ ! -x "$HOME/.local/bin/uv" ]]; then
    curl -LsSf https://astral.sh/uv/install.sh | sh >/dev/null
  fi
  export PATH="$HOME/.local/bin:$PATH"
  uv venv --python 3.11 .venv >/dev/null
  # Explicit CUDA index: the default PyPI wheel is not guaranteed to carry kernels
  # for the newest architectures.
  # Also not -q: this path additionally downloads torch itself, so silence is worse.
  uv pip install --index-strategy unsafe-best-match --extra-index-url "$CUDA_INDEX" \
    -e ".[train,bench]"
  LLMFS_PY="$REPO/.venv/bin/python"
fi

# How gpu.sh should invoke things. Written rather than assumed, so the driver does
# not have to guess which of the two paths above was taken.
BIN_DIR="$("$LLMFS_PY" -c 'import sysconfig;print(sysconfig.get_path("scripts"))')"
cat > "$WORKDIR/env.sh" <<EOF
# Generated by bootstrap.sh — how to run llmfs on this pod.
export LLMFS_PYTHON="$LLMFS_PY"
export PATH="$BIN_DIR:\$PATH"
EOF
echo "wrote $WORKDIR/env.sh (python: $LLMFS_PY)"

# ------------------------------------------------------------------ verification

echo "--- verifying the GPU is usable, and measuring it ---"
"$LLMFS_PY" - <<'PY'
import sys, time, torch

print("torch:", torch.__version__, "| cuda:", torch.version.cuda)
if not torch.cuda.is_available():
    sys.exit("FATAL: torch cannot see a GPU. The job would silently run on CPU.")

props = torch.cuda.get_device_properties(0)
arch = f"sm_{props.major}{props.minor}"
print(f"gpu: {torch.cuda.get_device_name(0)}  {props.total_memory/2**30:.0f} GiB  {arch}")
print("bf16 supported:", torch.cuda.is_bf16_supported())

supported = torch.cuda.get_arch_list()
print("torch was built for:", ", ".join(supported))
if arch not in supported and not any(a.startswith(f"sm_{props.major}") for a in supported):
    sys.exit(
        f"FATAL: this torch has no kernels for {arch}. Every matmul would fail.\n"
        f"       Use a pod template whose torch matches the card, or set\n"
        f"       CUDA_INDEX to a build that includes {arch}."
    )

# A real, large matmul. This is the number that decides whether the GPU choice was
# right — compare it against the estimates in docs/gpu-runbook.md before committing
# to a multi-hour job.
a = torch.randn(8192, 8192, device="cuda", dtype=torch.bfloat16)
for _ in range(3):
    a @ a
torch.cuda.synchronize()
t = time.perf_counter()
for _ in range(30):
    a @ a
torch.cuda.synchronize()
tflops = 30 * 2 * 8192**3 / (time.perf_counter() - t) / 1e12
print(f"\nMEASURED bf16 matmul: {tflops:,.0f} TFLOP/s")
print("  (docs/gpu-runbook.md assumes ~105 TF/s for an RTX 5090, ~989 for an H100 SXM;")
print("   if this is far below the assumption, re-read the cost table before running.)")
PY

echo "--- building the model on the GPU ---"
"$LLMFS_PY" -c "
from llmfs.config import load_config
from llmfs.model import Transformer
import torch
c = load_config('gpt2-124m'); m = Transformer(c.model).cuda()
free, total = torch.cuda.mem_get_info()
print(f'gpt2-124m: {m.num_params()/1e6:.1f}M params on GPU')
print(f'vram: {(total-free)/2**30:.1f} GiB used / {total/2**30:.0f} GiB total')
"

echo "bootstrap complete"
