"""Export real parameter counts, so the site's size calculator cannot drift.

The calculator is arithmetic over shapes: an embedding table here, a fused QKV
projection there, two norms per block. Every one of those is a place to be quietly
wrong by a bias vector or a factor of two — and being quietly wrong is worse in a
teaching tool than in a library, because the reader has no way to check it.

So the counts come from instantiating the real ``Transformer`` and summing
``p.numel()``. ``web/src/lib/modelsize.test.ts`` asserts the TypeScript reproduces
them exactly, for configurations chosen to move every switch that changes the total.

    python scripts/dump_model_sizes.py
"""

from __future__ import annotations

import json
from pathlib import Path

from llmfs.model import ModelConfig, Transformer

OUT = Path(__file__).resolve().parents[1] / "web" / "src" / "data" / "model-sizes.json"

# Each entry flips something that changes the parameter count: tying, bias terms,
# the norm type, the position scheme, the MLP (and its 2/3 correction), and GQA.
CASES: dict[str, dict] = {
    "gpt2-124m": {},
    "llama-124m": {
        "n_kv_head": 4,
        "norm": "rmsnorm",
        "pos_emb": "rope",
        "mlp": "swiglu",
        "bias": False,
    },
    "untied": {"tie_embeddings": False},
    "no-bias": {"bias": False},
    "rmsnorm": {"norm": "rmsnorm"},
    "rope": {"pos_emb": "rope"},
    "no-positions": {"pos_emb": "none"},
    "swiglu": {"mlp": "swiglu"},
    "gqa-2": {"n_kv_head": 2},
    "mqa": {"n_kv_head": 1},
    "ablation-base": {
        "vocab_size": 50304,
        "n_layer": 8,
        "n_head": 8,
        "n_embd": 512,
        "block_size": 512,
    },
    "tiny": {
        "vocab_size": 512,
        "n_layer": 2,
        "n_head": 2,
        "n_embd": 64,
        "block_size": 128,
    },
}

FIELDS = [
    "vocab_size",
    "n_layer",
    "n_head",
    "n_kv_head",
    "n_embd",
    "block_size",
    "norm",
    "pos_emb",
    "mlp",
    "tie_embeddings",
    "bias",
    "mlp_ratio",
    "mlp_hidden_multiple_of",
]


def build() -> str:
    """The fixture's exact text, separated from the write so a test can diff it."""
    cases = []
    for name, overrides in CASES.items():
        cfg = ModelConfig(**overrides)
        model = Transformer(cfg)
        # Tied weights are one tensor shared by two modules; `parameters()` already
        # deduplicates, which is exactly the semantics the calculator must match.
        total = sum(p.numel() for p in model.parameters())
        cases.append(
            {
                "name": name,
                "config": {f: getattr(cfg, f) for f in FIELDS},
                "head_dim": cfg.head_dim,
                "mlp_hidden": cfg.mlp_hidden,
                "total_params": total,
            }
        )
        print(f"{name:<14} {total:>12,} params")

    return (
        json.dumps(
            {
                "_comment": (
                    "Generated by scripts/dump_model_sizes.py from llmfs.model.Transformer. "
                    "Do not hand-edit: regenerate it."
                ),
                "cases": cases,
            },
            indent=2,
        )
        + "\n"
    )


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build())
    print(f"\nwrote {OUT}")


if __name__ == "__main__":
    main()
