"""Generate the fixture that pins the site's TypeScript RoPE port to this one.

The attention explorer and the RoPE explorer are only worth anything if they show
the model that this repository actually trains. The explorer runs in a browser, so
its rotation math is a second implementation in TypeScript — and a second
implementation is a liability the moment it drifts from the first.

This writes a small set of rotated vectors and attention logits produced by
``llmfs.model.rope``. ``web/src/lib/rope.test.ts`` asserts the TypeScript port
reproduces them, and ``tests/test_rope.py`` asserts the committed fixture still
matches Python — so a change to either side that is not mirrored in the other
fails CI, rather than quietly making the visualization a lie.

    python scripts/dump_rope_fixture.py
"""

from __future__ import annotations

import json
from pathlib import Path

import torch

from llmfs.model.rope import RotaryEmbedding, apply_rotary_emb

FIXTURE = Path(__file__).resolve().parents[1] / "web" / "src" / "data" / "rope-fixture.json"

HEAD_DIM = 16
THETA = 10_000.0
# Positions chosen to cover: the identity case (0), a short gap, a long gap, and two
# different absolute positions sharing one offset — which is the property under test.
CASES = [(0, 0), (5, 0), (5, 3), (12, 10), (64, 62), (200, 7)]


def build() -> dict:
    torch.manual_seed(0)
    q = torch.randn(HEAD_DIM, dtype=torch.float64)
    k = torch.randn(HEAD_DIM, dtype=torch.float64)
    q = q / q.norm()
    k = k / k.norm()

    rope = RotaryEmbedding(head_dim=HEAD_DIM, max_seq_len=8, theta=THETA)

    cases = []
    for m, n in CASES:
        # (B, n_head, T, head_dim) with a single token, so `offset` carries the
        # position — exactly the shape the KV-cache decode path uses.
        cos_q, sin_q = rope(seq_len=1, offset=m)
        cos_k, sin_k = rope(seq_len=1, offset=n)
        qv = q.view(1, 1, 1, HEAD_DIM)
        kv = k.view(1, 1, 1, HEAD_DIM)
        q_rot, _ = apply_rotary_emb(qv, qv, cos_q.double(), sin_q.double())
        k_rot, _ = apply_rotary_emb(kv, kv, cos_k.double(), sin_k.double())
        q_rot = q_rot.reshape(HEAD_DIM)
        k_rot = k_rot.reshape(HEAD_DIM)
        cases.append(
            {
                "m": m,
                "n": n,
                "q_rot": q_rot.tolist(),
                "k_rot": k_rot.tolist(),
                "logit": float(torch.dot(q_rot, k_rot)),
            }
        )

    return {
        "_comment": (
            "Generated by scripts/dump_rope_fixture.py from llmfs.model.rope. "
            "Do not hand-edit: regenerate it."
        ),
        "convention": "split-half",
        "head_dim": HEAD_DIM,
        "theta": THETA,
        "q": q.tolist(),
        "k": k.tolist(),
        "cases": cases,
    }


def main() -> None:
    payload = build()
    FIXTURE.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {FIXTURE} ({len(payload['cases'])} cases)")


if __name__ == "__main__":
    main()
