"""Extract the reproduction run's loss curve into a committed artifact.

The run wrote ``out/gpt2-124m-repro/metrics.jsonl``, and ``out/`` is gitignored — it
holds checkpoints and logs measured in gigabytes. So the curve behind
``results/reproduction_curve.png`` existed only on the machine that rented the H100,
which is fine for a plot that was rendered once and fine for nothing else. The site's
reproduction plate needs the series itself: a reader dragging a scrubber across the run
is reading the log, not a picture of it.

This lifts the two series out into ``results/reproduction-curve.json``, alongside the
scalar figures already in ``results/reproduction.json``, so the curve becomes an
artifact like every other number the site is allowed to state.

    python scripts/dump_reproduction_curve.py

Re-running it needs the original ``metrics.jsonl``. That is the same constraint every
file in ``results/`` carries — none of them can be regenerated without the hardware
that produced them — and it is why they are committed rather than built.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
METRICS = ROOT / "out" / "gpt2-124m-repro" / "metrics.jsonl"
OUT = ROOT / "results" / "reproduction-curve.json"

# Pre-registered in the header of `configs/gpt2-124m.yaml`, before the run.
TARGET_LOSS = 3.29


def main() -> None:
    if not METRICS.exists():
        raise SystemExit(f"{METRICS} not present — this needs the original run's log")

    rows = [json.loads(line) for line in METRICS.read_text().splitlines() if line.strip()]
    train = [
        {"step": r["step"], "loss": r["train/loss"], "mfu": r.get("perf/mfu")}
        for r in rows
        if "train/loss" in r
    ]
    val = [
        {"step": r["step"], "loss": r["val/loss"], "perplexity": r["val/perplexity"]}
        for r in rows
        if "val/loss" in r
    ]
    if not train or not val:
        raise SystemExit("the log holds no train or no val points")

    # The step at which the pre-registered target was first met. Recorded rather than
    # left to the reader's arithmetic, because "34% of the way in" is the claim the
    # plate makes and a claim should not be computed twice in two languages.
    crossing = next((p for p in val if p["loss"] <= TARGET_LOSS), None)
    last = train[-1]

    payload = {
        "_comment": (
            "Generated by scripts/dump_reproduction_curve.py from the run's "
            "out/gpt2-124m-repro/metrics.jsonl. Do not hand-edit."
        ),
        "targetLoss": TARGET_LOSS,
        "finalStep": last["step"],
        "tokens": next(r["progress/tokens"] for r in reversed(rows) if "progress/tokens" in r),
        "crossing": crossing and {**crossing, "fractionOfRun": crossing["step"] / last["step"]},
        "train": train,
        "val": val,
    }

    # Compact: nearly two thousand points, indented, is 170 KB of whitespace for a file
    # no one reads by eye and that is regenerated wholesale rather than edited.
    OUT.write_text(json.dumps(payload, separators=(",", ":")) + "\n")
    crossed = payload["crossing"]
    print(f"wrote {OUT.relative_to(ROOT)}  ({len(train)} train, {len(val)} val points)")
    if crossed:
        print(f"  target {TARGET_LOSS} first met at step {crossed['step']:,} "
              f"({crossed['fractionOfRun']:.1%} of the run)")


if __name__ == "__main__":
    main()
