"""Count what follows what in this repository's corpus, for the explainer.

The sampling section needs a next-token distribution to play with. Inventing one
would have been easier, and would have quietly broken the rule the rest of the site
runs on: nothing is shown as measured unless it was measured.

So this counts. It tokenizes ``data/wizard_of_oz.txt`` with the same GPT-2
vocabulary the models use and records, for a handful of common contexts, which
tokens actually followed — a bigram model, the simplest language model there is and
the one this repository began as (``notebooks/bigram.ipynb``).

That makes the explainer's arc honest rather than rhetorical: the reader samples
from a real distribution, sees temperature and top-k do real work, and then sees the
thing a bigram cannot do — look further back than one token — which is the problem
attention exists to solve.

    python scripts/dump_bigram.py
"""

from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path

import tiktoken

ROOT = Path(__file__).resolve().parents[1]
CORPUS = ROOT / "data" / "wizard_of_oz.txt"
OUT = ROOT / "web" / "src" / "data" / "bigram.json"

# Contexts common enough in this corpus to have a distribution worth looking at, and
# varied enough to show different shapes: an almost-deterministic one, a wide-open
# one, and a few in between.
CONTEXTS = [
    " the",
    " a",
    " Dorothy",
    " to",
    " was",
    " said",
    " Scarecrow",
    " green",
    " Emerald",
    " and",
]
TOP_N = 24


def main() -> None:
    if not CORPUS.exists():
        raise SystemExit(f"corpus not found: {CORPUS}")

    enc = tiktoken.get_encoding("gpt2")
    ids = enc.encode(CORPUS.read_text())

    following: dict[int, Counter[int]] = defaultdict(Counter)
    for current, nxt in zip(ids, ids[1:]):
        following[current][nxt] += 1

    entries = []
    for context in CONTEXTS:
        context_ids = enc.encode(context)
        if len(context_ids) != 1:
            # Not a failure, and a nice illustration of the first lesson: " Scarecrow"
            # looks like one word but is two tokens, so it has no single-token
            # distribution to show. Skip it and say why.
            print(f"skipping {context!r}: {len(context_ids)} tokens, not one")
            continue
        token_id = context_ids[0]
        counts = following.get(token_id)
        if not counts:
            print(f"skipping {context!r}: never appears in the corpus")
            continue

        total = sum(counts.values())
        top = counts.most_common(TOP_N)
        entries.append(
            {
                "context": context,
                "context_id": token_id,
                "occurrences": total,
                "distinct_followers": len(counts),
                # `covered` is what share of the real distribution the shipped top-N
                # accounts for. Truncating silently would overstate how confident the
                # model is, so the page states it.
                "covered": sum(c for _, c in top) / total,
                "candidates": [{"id": i, "text": enc.decode([i]), "count": c} for i, c in top],
            }
        )
        print(f"{context!r:<14} {total:>5} occurrences, {len(counts):>4} distinct followers")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "_comment": (
                    "Generated by scripts/dump_bigram.py from data/wizard_of_oz.txt. "
                    "Do not hand-edit: regenerate it."
                ),
                "source": "data/wizard_of_oz.txt",
                "encoding": "gpt2",
                "total_tokens": len(ids),
                "entries": entries,
            },
            ensure_ascii=False,
            indent=1,
        )
        + "\n"
    )
    print(f"\nwrote {OUT} ({len(ids):,} tokens counted)")


if __name__ == "__main__":
    main()
