"""Export the GPT-2 vocabulary for the browser, plus a fixture pinning the TS port.

The explainer's first lesson is that the model does not see text, it sees tokens —
and that lesson only lands if the reader can type their own sentence and watch it
split. That needs a real tokenizer in the browser, not a curated list of examples.

Shipping ``data/bpe_tokenizer.json`` is not an option at 10 MB. But tiktoken-style
BPE needs only one thing: a map from token bytes to rank. Given that, encoding is
"repeatedly merge the adjacent pair whose combined bytes have the lowest rank",
which the TypeScript port implements directly. So the whole vocabulary is exportable
as an array of 50,257 strings indexed by token id — about 1 MB raw, and the site
loads it lazily so only readers who open the explainer pay for it.

Bytes are written using GPT-2's own byte-to-unicode mapping (the same representation
as the original ``vocab.json``), which keeps every token a valid JSON string without
base64 inflating it.

    python scripts/dump_tokenizer.py
"""

from __future__ import annotations

import json
from pathlib import Path

import tiktoken

ROOT = Path(__file__).resolve().parents[1]
VOCAB_OUT = ROOT / "web" / "src" / "data" / "gpt2-vocab.json"
FIXTURE_OUT = ROOT / "web" / "src" / "data" / "tokenizer-fixture.json"

# Texts chosen to exercise what actually breaks a BPE port: leading spaces (the
# single most common source of off-by-one vocabularies), casing, digits grouped in
# threes, contractions, punctuation runs, non-ASCII, emoji outside the BMP, and
# newlines.
FIXTURE_TEXTS = [
    "Dorothy lived in the midst of the great Kansas prairies.",
    " leading space",
    "no_leading_space",
    "The cat sat on the mat.",
    "Attention is all you need",
    "GPT-2 has 50,257 tokens in its vocabulary.",
    "don't can't won't it's",
    "Hello,   world!!!  ...",
    "3.14159 and 1234567890",
    "CamelCase snake_case SCREAMING_CASE",
    "café naïve résumé — em-dash",
    "emoji: 🙂🚀",
    "line one\nline two\n\tindented",
    "",
]


def bytes_to_unicode() -> dict[int, str]:
    """GPT-2's reversible byte→printable-character map.

    Bytes that are not printable get shifted into a private range, so a token's raw
    bytes survive a round trip through JSON without escaping every other character.
    """
    bs = (
        list(range(ord("!"), ord("~") + 1))
        + list(range(ord("¡"), ord("¬") + 1))
        + list(range(ord("®"), ord("ÿ") + 1))
    )
    cs = bs[:]
    n = 0
    for b in range(2**8):
        if b not in bs:
            bs.append(b)
            cs.append(2**8 + n)
            n += 1
    return {b: chr(c) for b, c in zip(bs, cs)}


def main() -> None:
    enc = tiktoken.get_encoding("gpt2")
    byte_encoder = bytes_to_unicode()

    # Rank == token id for every mergeable token; the specials sit above them.
    vocab: list[str | None] = [None] * enc.n_vocab
    for token_bytes, rank in enc._mergeable_ranks.items():
        vocab[rank] = "".join(byte_encoder[b] for b in token_bytes)
    for special, rank in enc._special_tokens.items():
        vocab[rank] = special

    missing = [i for i, v in enumerate(vocab) if v is None]
    if missing:
        raise SystemExit(f"vocabulary has {len(missing)} unfilled ids, first at {missing[0]}")

    VOCAB_OUT.parent.mkdir(parents=True, exist_ok=True)
    VOCAB_OUT.write_text(json.dumps(vocab, ensure_ascii=False, separators=(",", ":")))

    fixture = {
        "_comment": (
            "Generated by scripts/dump_tokenizer.py from tiktoken's gpt2 encoding. "
            "Do not hand-edit: regenerate it."
        ),
        "encoding": "gpt2",
        "n_vocab": enc.n_vocab,
        "eot_token": enc.eot_token,
        "cases": [{"text": t, "ids": enc.encode(t)} for t in FIXTURE_TEXTS],
    }
    FIXTURE_OUT.write_text(json.dumps(fixture, ensure_ascii=False, indent=2) + "\n")

    size_mb = VOCAB_OUT.stat().st_size / 1024**2
    print(f"wrote {VOCAB_OUT.name} ({enc.n_vocab} tokens, {size_mb:.2f} MB)")
    print(f"wrote {FIXTURE_OUT.name} ({len(FIXTURE_TEXTS)} cases)")


if __name__ == "__main__":
    main()
